### PR TITLE
save progress more frequently

### PR DESCRIPTION
**Pull request by liyuankui**

### CODE REVIEW

**Comment by yihong0618** [comment]
Can you explain why you modified it ？

**Comment by liyuankui** [comment]
Without this PR, progress is only saved when SIGINT received. 
However, during my local tinkering, other issues might disturb the process, losing all unsaved translations; I add this PR to save progress every 50 translations. It's like auto-save for Word.

**Comment by yihong0618** [comment]
make sense 50 seems a little big? let's make it 30?

**Comment by yihong0618** [comment]
merged first I will change it to 30

**Pull request merged**
