### PR TITLE
Feat/add target lang choices

### PR DESCRIPTION
**Pull request by MIBlue119**
At #8 , @yihong0618  mentioned a feature about supporting traditional chinese.

1. Add a new argument `language` to let user set target language
2. Borrow the language code and language mapping dictionary from https://github.com/openai/whisper
3. Add the language as a attribute to class

### CODE REVIEW

**Comment by yihong0618** [comment]
amazing work will take a look later.
and we have CI now can you add small test too

with your arg and “—test —test_num 2” at the end of CI yml file？

**Comment by MIBlue119** [comment]
@yihong0618  Thanks for your message, I added the argument to the yaml

**Comment by yihong0618** [comment]
@MIBlue119 after merge last PR there's some conflict
will push one commit, can you check is that OK?

**Comment by yihong0618** [comment]
@MIBlue119 after some test 
we can not use `short here`
like --language ja -> ChatGPT Sometimes I don't recognize him
let us use long name  `--language japanese` or `--language "traditional chinese",` instead
image

**Comment by MIBlue119** [comment]
> @MIBlue119 after merge last PR there's some conflict will push one commit, can you check is that OK?

@yihong0618 Thanks for your conflict solving. I agree with your changes about the language settings to complete string~

**Comment by yihong0618** [comment]
@MIBlue119 I just finished it please.
And can you add some info to README? 
you can add it in English, I think it's OK.

Add your work here
image

**Comment by yihong0618** [comment]
@MIBlue119 can this merge now?
LGTM

**Comment by MIBlue119** [comment]
> @MIBlue119 I just finished it please. And can you add some info to README? you can add it in English, I think it's OK.
> 
> Add your work here image

Thanks, I added some descriptions ~

**Comment by MIBlue119** [comment]
> LGTM

I am very happy to participate in a part of the implementation, thank you for this project

**Comment by yihong0618** [comment]
Thanks very much
then I will figure out why `secret` do not work here....

**Pull request merged**
