### PR TITLE
替 BBM_CHATGPTAPI_SYS_MSG 與 BBM_CHATGPTAPI_USER_MSG_TEMPLATE 加入斷行能力

### LINKED ISSUE #223: 替 BBM_CHATGPTAPI_SYS_MSG 與 BBM_CHATGPTAPI_USER_MSG_TEMPLATE 加入斷行能力
目前 `BBM_CHATGPTAPI_SYS_MSG` 與 `BBM_CHATGPTAPI_USER_MSG_TEMPLATE` 無法斷行，比較不方便，我等等會上一個 PR 增加斷行能力，只要在 Prompt 加上 `{crlf}` 就會自動替換成斷行符號 ( `\n` )

### PR DESCRIPTION
**Pull request by doggy8088**
Fixes #223

### CODE REVIEW

**Comment by yihong0618** [comment]
can you fix the lint(^-^)

**Comment by doggy8088** [comment]
I couldn't find any code needs to reformat.

**Comment by yihong0618** [comment]
pip install -U black
black .

**Comment by doggy8088** [comment]
Done. Thanks!

**Comment by yihong0618** [comment]
thanks

**Pull request merged**
