### PR TITLE
feat: support claude model

### PR DESCRIPTION
**Pull request by jtsang4**
* Support Anthropic's [Claude](https://console.anthropic.com/docs) model.
* By the way, fixed the incorrect deepl call method in the documentation.

### CODE REVIEW

**Comment by yihong0618** [comment]
@jtsang4 thanks

**Comment by yihong0618** [comment]
very neat code, thanks

**Comment by joostshao** [comment]
how to get claude's api key ? i am still in the waitlist ~

**Comment by jtsang4** [comment]
> how to get claude's api key ? i am still in the waitlist ~

It's lottery, all depends on luck. 😂

**Pull request merged**
