### PR TITLE
feat: add txt book loader

### PR DESCRIPTION
**Pull request by zstone12**
主要参考 https://github.com/yihong0618/bilingual_book_maker/pull/35 实现txt loader。
目前用the_little_prince.txt 测试，效果正常。

TODO：
- [x] 完善 _save_temp_book 实现
- [x] txt 类型补充到文档中

### CODE REVIEW

**Comment by yihong0618** [comment]
@zstone12 
for this PR I think its OK.
in the future can we batch the lines
like `line1+;;;+line2+;;;+line3+;;; -> to bantch translate -> back we split it then add to the book?
 txt is relatively better to control

**Comment by zstone12** [comment]
> @zstone12 for this PR I think its OK. in the future can we batch the lines like `line1+;;;+line2+;;;+line3+;;; -> to bantch translate -> back we split it then add to the book? txt is relatively better to control
This sounds better, it will improve efficiency, and we can complete it in the later work.

**Comment by zstone12** [comment]
> @zstone12 for this PR I think its OK. in the future can we batch the lines like `line1+;;;+line2+;;;+line3+;;; -> to bantch translate -> back we split it then add to the book? txt is relatively better to control

@yihong0618 This sounds better, it will improve efficiency, and we can complete it in the later work.

**Comment by zstone12** [comment]
@DennySORA  This PR is based on your work. Thanks for your previous work.

**Pull request merged**
