### PR TITLE
MakeFile easy to test local

### PR DESCRIPTION
**Pull request by YYLIZH**
#192
 
# Change
1. refactor the test flow into unittests
2. add a Makefile for local test
Since I don't have api permission, @yihong0618 could you help me test the Makefile?

# Need to discuss
I notice that the packages in requirements.txt and install_requires are not consistent, so I add a fix here. If @yihong0618 you are intend to let this happen, I can delete the fix.

# Future enhancement
1. Add linter like pylint or flake in both Makefile and github workflow
https://github.com/yihong0618/bilingual_book_maker/blob/45bfdf7907518b0579313560af80323e7f1e9b55/book_maker/obok.py#L264
I noticed that this package imported in source code but not listed in requirements.txt. Add linter may avoid this bug.
 
2. Break the github workflow
github workflow can break into "linter" and "tests".
"linter" can include isort, black, autoflake, which can directly format the codes and commit.
"tests" can run tests.

### CODE REVIEW

**Comment by yihong0618** [comment]
@YYLIZH can you read env in test that we can ignore the tests use `TOKEN` like my old one in yml?

**Comment by yihong0618** [comment]
that can make your  Actions pass

**Comment by YYLIZH** [comment]
Got it. I will adjust the code next Monday.

**Comment by YYLIZH** [comment]
@yihong0618 CI pass now.

**Review by yihong0618 — APPROVED** [review]
nice

**Comment by yihong0618** [comment]
@YYLIZH https://github.com/yihong0618/bilingual_book_maker/actions/runs/4791631282/jobs/8522261742

**Pull request merged**
