### PR TITLE
Add support for Llama2, Palm, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@yihong0618 can you please take a look when you get the chance, happy to add additional docs/changes based on your feedback

**Comment by yihong0618** [comment]
can you just name it LLM instead of littleLLM

**Comment by yihong0618** [comment]
can you fix the lint?

pip install -U black
black .

**Comment by yihong0618** [comment]
> @yihong0618 can you please take a look when you get the chance, happy to add additional docs/changes based on your feedback

of course, Happy to see this work

**Comment by ishaan-jaff** [comment]
@yihong0618 fixed. Any feedback on integrating this for calling models ? or the best way to do that ?

**Comment by yihong0618** [comment]
code LGTM
can you add the info to README?

**Comment by ishaan-jaff** [comment]
@yihong0618 just updated the Readme

**Comment by YYLIZH** [comment]
Hi @ishaan-jaff. I am trying to integrate this into documentation. However, the readme is confusing for me. 
1. How to use this in the command line?
2. The link in the Supported Models section is missing.

**Pull request merged**
