### PR TITLE
feature: GPT-4 support

### PR DESCRIPTION
**Pull request by astromaddie**
Added GPT-4 as an option, may add additional features to this file later to take advantage of the doubled (8k) token limit

### CODE REVIEW

**Comment by astromaddie** [comment]
I see, I need to install black and run `black make_book.py`

I will fix this!

**Comment by astromaddie** [comment]
@yihong0618 sorry to be annoying today :)
this is my first time using black.

`bilingual_book_maker % black make_book.py
All done! ✨ 🍰 ✨
1 file left unchanged.`

Is there something I am doing wrong?

**Comment by yihong0618** [comment]
thanks will take a look tonight

**Comment by yihong0618** [comment]
@astromaddie most code are the same as gpt3? why do we just change the gpt3?

**Comment by yihong0618** [comment]
also use chatgptapi and add one arg

--use_gpt4 store_true

**Comment by astromaddie** [comment]
> @astromaddie most code are the same as gpt3? why do we just change the gpt3?

yeah, it turned out the the only difference between accessing the two models is changing the actual model call. I thought about adding it as a flag for chatgptapi like you suggested, but I want to modify it more heavily to support adding context paragraphs in the prompt, which would take up a lot of the already limited token limits for GPT3. (GPT3 supports 4k tokens including input, system prompt, and output, but GPT4 supports 8k tokens.)

it’s your project so we can integrate it into the chatgptapi method if you’re not interested in the context prompt, I can always just add that in my own fork for personal use :)

**Comment by hleft** [comment]
What is the difference between adding context  paragraphs for gpt4 and what -`-accumulated_num` provides?

**Comment by astromaddie** [comment]
> What is the difference between adding context paragraphs for gpt4 and what `--accumulated_num` provides?

`--accumulated_num` increases how many paragraphs are passed into the language model at one time to translate, which improved the quality of the translation, but any context before that is lost (e.g. `--accumulated_num 1200` will pass up to 1200 tokens at a time, but when passing tokens 1201-2400, you lose the context of tokens 1-1200. What I’m working on solving is a context paragraph that summarises the main points of tokens 1-1200, and prefaces the next 1200 tokens with it, then revised the context paragraph to include a summary of all 2400 tokens for the next 1200 tokens, etc. Conceptually, it works well, I just need to get it written into the code.

**Comment by astromaddie** [comment]
Updated the gpt4 translator to use the context functionality, it can be enabled with `--use_context`. This could be added to other models but I'm concerned it would use up too many tokens for chatgptapi, for instance, so I think it's better to keep it exclusive to GPT-4. I find this results in a smoother translation with more consistent tone.

**Comment by yihong0618** [comment]
@astromaddie thanks, I will take a look later and try to make the code easier base on your PR.

**Review by Jackie00765 — APPROVED** [review]

**Pull request merged**
