### PR TITLE
fix

### PR DESCRIPTION
**Pull request by hleft**
None is not of type 'string' - 'messages.0.content' will sleep 2 seconds

### CODE REVIEW

**Comment by yihong0618** [comment]
@hleft nice catch

**Comment by yihong0618** [comment]
Thanks a lot for these days
@hleft hi do you want to be collaborators if that I will invite you.

**Comment by hleft** [comment]
@yihong0618 I do, thank you for such a useful project, it was a pleasure working together

**Comment by yihong0618** [comment]
Done, please check the email later.

**Pull request merged**
